name: Full PHP Compatibility Tests

on:
  push:
    branches: [ 2025.5-code-update ]
  pull_request:
    branches: [ 2025.5-code-update ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4']
    name: PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Validate PHP version
        run: php -v

      - name: Run manual test on PHP < 8.2
        if: matrix.php != '8.2' && matrix.php != '8.3' && matrix.php != '8.4'
        run: |
          php -r "
          require 'src/Crypto.php';
          \$crypto = new Crypto\\Crypto('test', 'iv', true);
          \$result = \$crypto->decrypt(\$crypto->encrypt('Hello'));
          if (\$result !== 'Hello') { exit(1); }
          "

      - name: Install dev dependencies
        if: matrix.php == '8.2' || matrix.php == '8.3' || matrix.php == '8.4'
        run: composer install --no-progress --prefer-dist

      - name: Run full Pest test suite
        if: matrix.php == '8.2' || matrix.php == '8.3' || matrix.php == '8.4'
        run: ./vendor/bin/pest
